USE master;

CREATE DATABASE PRUEBA_VACUNAS;

USE PRUEBA_VACUNAS;

CREATE TABLE VACUNA(
	ID_VACUNA INT IDENTITY(1,1),
	NOMBRE_VACUNA VARCHAR(30) NOT NULL,
	DIAS_POST_PRIMERA_DOSIS INT NOT NULL,
	DOSIS_UNICA BIT NOT NULL,
	CONSTRAINT PK_VACUNA
		PRIMARY KEY(ID_VACUNA)
);

CREATE TABLE PUESTO(
	ID_PUESTO INT IDENTITY(1,1),
	NOMBRE_PUESTO VARCHAR(30) NOT NULL,
	CONSTRAINT PK_PUESTO
		PRIMARY KEY (ID_PUESTO)
);

CREATE TABLE EMPLEADO(
	ID_EMPLEADO INT IDENTITY(1,1),
	ID_PUESTO INT NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	CONSTRAINT PK_EMPLEADO
		PRIMARY KEY(ID_EMPLEADO),
	CONSTRAINT FK_EMPLEADO_PUESTO
		FOREIGN KEY (ID_PUESTO) REFERENCES PUESTO(ID_PUESTO)
)

CREATE TABLE REPORTE_VACUNAS(
	NO_LINEA INT IDENTITY(1,1),
	ID_EMPLEADO INT NOT NULL,
	ID_VACUNA INT NOT NULL,
	FECHA_1DOSIS DATETIME,
	FECHA_2DOSIS DATETIME,
	ESTADO_VACUNA BIT,
	CONSTRAINT FK_EMPLEADO_REPORTE
		FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
	CONSTRAINT FK_VACUNA_REPORTE
		FOREIGN KEY (ID_VACUNA) REFERENCES VACUNA(ID_VACUNA)
)

--Carga inicial
INSERT INTO PUESTO VALUES ('Empleado'), ('Secretaria'),('Piloto'), ('Gerente')
